<div class="pagehding-sec" style='background-image: url("<?php echo $this->basePath('pictures/templates/' . $template[36]['template_picture']);?>")'>
    <div class="pagehding-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-heading">
                    <h1><?php echo $this->escapeHtml($postCategory['category_name_' . $lang]);?></h1>
                    <?php echo $crum;?>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="about-us-sec pt-100 pb-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="abt-img">
                    <img src="<?php echo $this->basePath('pictures/posts/' . $post['post_picture']);?>" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="abt-lft">
                    <h2><?php echo $this->escapeHtml($post['post_title_' . $lang]);?></h2>
                    <?php echo $post['post_body_' . $lang];?>
                </div>
            </div>
            <div class="col-lg-12">
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.0&appId=145168662811769&autoLogAppEvents=1';
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="10" width="100%"></div>
            </div>
        </div>
    </div>
</div>

<?php if (count($postOther) > 0) {?>
<div class="service-sec pt-100 pb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sec-title">
                    <h1><?php echo $this->translate('other service');?></h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="service-item">
                <?php foreach($postOther as $v) {?>
                <div class="col-md-4 col-sm-6">
                    <div class="service-inner">
                        <div class="service-img" style="background-image: url('img/g1.jpg'); background-size: cover; background-position: center center;">
                        </div>
                        <div class="service-details">
                            <h2><a href="<?php echo $this->url('home-service-detail', array('name' => $this->function()->formatTitle($v['post_title_' . $lang]), 'id' => $v['post_id']));?>"><?php echo $this->escapeHtml($v['post_title_' . $lang]);?></a></h2>
                            <?php echo $v['post_quote_' . $lang];?>
                        </div>
                    </div>
                </div>
                <?php }?>

            </div>
        </div>
    </div>
</div>
    <?php }?>