<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <?php echo $this->partial('admin/partial/language'); ?>

        <?php echo $this->formViewElement($form->get('template_name'));?>

        <?php echo $this->formViewElement($form->get('template_title_vn'), null, ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('template_title_en'), null, ['formGroupClass' => 'field-en']);?>

        <?php echo $this->formViewElement($form->get('template_picture'), 'picture', [
            'pictureValue' => $record['template_picture'],
            'recordId' => $record['template_id'],
            'pictureUrl' => 'public/pictures/templates/',
            'pictureDelUrl' => $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture')),
        ]);?>

        <?php echo $this->formViewElement($form->get('template_content_vn'), null, ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('template_content_en'), null, ['formGroupClass' => 'field-en']);?>

        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="template_multi_picture">Hình ảnh Slide</label>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <div id="multi_picture_show">
                    <?php if (!empty($templatePictures)) {
                        foreach($templatePictures as $templatePicture) {?>
                            <img title="Click để xóa" class="img-rounded post-img" id="template_multi_<?php echo $templatePicture['template_picture_id']; ?>" onclick="deletePictureMulti(<?php echo $templatePicture['template_picture_id']; ?>)"
                                 style="cursor: pointer; margin: 0 5px 5px"
                                 src="<?php echo $this->serverUrl() . '/thumbs/timthumb.php?src=' . $this->basePath('public/pictures/templates/' . $templatePicture['template_picture_name']) . '&w=100px&h=100px'; ?>"/>
                    <?php }}?>
                    <p><input name="template_multi_picture[]" type="file" class="form-control"></p>

                </div>

                <button type="button" class="btn btn-warning btn-xs" id="btnMultiPicture" style="float: right; margin: 10px 0"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Thêm</button>
            </div>

        </div>

        <?php echo $this->formViewElement($form->get('template_status'));?>

        <div class="ln_solid clear"></div>

        <div class="form-group">
            <div class="col-md-5 col-sm-5 col-xs-12 col-md-offset-3">
                <input type="button" onclick="location.href='<?php echo $this->url('admin/default', ['controller' => $module, 'action' => 'index'], array('query' => array('id' => $record['template_id'], 'group_template_id' => $groupTemplateId)));?>'" name="back" id="back" class="btn btn-default" value="Quay về">
                <?php echo $this->formReset($form->get('frmReset')); ?>
                <?php echo $this->formSubmit($form->get('frmSubmit')); ?>
                <?php echo $this->formHidden($form->get('csrf')); ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

<?php $this->inlineScript()->captureStart();?>
    $(function() {

        $('#btnMultiPicture').click(function(){
            $('#multi_picture_show').append('<p><input name="template_multi_picture[]" type="file" class="form-control"></p>');
        });
    });


function deletePictureMulti(id) {
if (confirm('Bạn có muốn xóa?')) {
$.ajax({
url: '<?php echo $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture-multi'));?>',
type: 'post',
data: {id: id},
success: function (response) {
data = jQuery.parseJSON(response);
if (data.return == 1) {
$('#template_multi_' + id).remove();
}
}
});
}
}
<?php $this->inlineScript()->captureEnd();?>


