
<form name="" id="frm_table" action="<?php echo $this->url('admin/default', ['controller' => $module]); ?>"
      method="post">
    <input type="hidden" name="group_template_id" value="<?php echo $groupTemplateId;?>">
    <div class="x_panel">
        <div class="x_title">
            <h2><?php echo $moduleName; ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a href="<?php echo $this->url('admin/default', ['controller' => $module, 'action' => 'add'], ['query' => ['group_template_id' => $groupTemplateId]]); ?>">
                        <button type="button" class="btn btn-primary">
                            Thêm mới
                        </button>
                    </a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <button type="button" onclick="location.href='<?php echo $this->url('admin/default', ['controller' => 'group-template']); ?>'" class="btn btn-info">Nhóm giao diện</button>
            <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
            <div class="table-responsive">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                        <tr class="headings">
                            <th><input type="checkbox" id="check-all" class="checkbox_all"></th>
                            <th class="column-title">Giao diện</th>
                            <th class="column-title">Trạng thái</th>
                            <th class="column-title">Chức năng</th>
                            <th id="bulk_delete_items" colspan="7">
                                <button type="button" class="btn btn-warning btn-xs no_margin_bottom" id="btn_delete_items">
                                    Xóa đã chọn
                                </button>
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php foreach ($records as $record) { ?>
                            <tr class="even pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="checkbox_item" name="check_item[]"
                                           value="<?php echo $record['template_id']; ?>">
                                </td>
                                <td>
                                    <?php echo '<a href="' . $this->url('admin/default', array('controller' => $module, 'action' => 'edit'), array('query' => array('id' => $record['template_id'], 'group_template_id' => $groupTemplateId))) . '"> <strong>' . $this->escapeHtml($record['template_name']) . '</strong>' . '</a>'; ?></td>
                                <td>
                                    <?php echo $status[$record['template_status']]; ?>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url('admin/default', array('controller' => $module, 'action' => 'edit'), array('query' => array('id' => $record['template_id'], 'group_template_id' => $groupTemplateId))); ?>"
                                       class="btn btn-info btn-xs btn-edit"><i class="fa fa-pencil"></i> Cập nhật </a>

                                    <a href="<?php echo $this->url('admin/default', array('controller' => $module, 'action' => 'delete'), array('query' => array('id' => $record['template_id'], 'group_template_id' => $groupTemplateId))); ?>"
                                       onclick="confirmDelete('deleteItem', this)" class="btn btn-danger btn-xs"><i
                                            class="fa fa-trash-o"></i> Xóa </a>
                                </td>
                            </tr>
                        <?php } ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <?php echo $this->paginationControl($paging, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/default', ['controller' => $module, 'action' => 'index'], ['query' => ['group_template_id' => $groupTemplateId]]))); ?>
        </div>
</form>
