<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <?php echo $this->formViewElement($form->get('menu_name'));?>
        <?php echo $this->formViewElement($form->get('menu_parent'));?>

        <?php echo $this->formViewElement($form->get('menu_url'));?>
        <?php echo $this->formViewElement($form->get('menu_icon'));?>

        <?php echo $this->formViewElement($form->get('menu_position'));?>
        <?php echo $this->formViewElement($form->get('menu_status'));?>

        <div class="ln_solid clear"></div>

        <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>








