<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <?php echo $this->partial('admin/partial/language'); ?>

        <?php echo $this->formViewElement($form->get('post_title_vn'), null, ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('post_title_en'), null, ['formGroupClass' => 'field-en']);?>
        <?php echo $this->formViewElement($form->get('post_body_vn'), 'textarea', ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('post_body_en'), 'textarea', ['formGroupClass' => 'field-en']);?>

        <?php echo $this->formViewElement($form->get('post_status'));?>

        <div class="ln_solid clear"></div>

        <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

<?php $this->inlineScript()->captureStart();?>
function deleteURL() {
$('input[type="file"]').val('');
$('.picture_upload_view').attr('src', no_image);
}

function deletePicture(id) {
if (confirm('Bạn có muốn xóa?')) {
$.ajax({
url: '<?php echo $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture'));?>',
type: 'post',
data: {id: id},
success: function (response) {
data = jQuery.parseJSON(response);
if (data.return == 1) {
$('#picture').remove();
}
}
});
}
}
<?php $this->inlineScript()->captureEnd();?>




