<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <?php
        if (empty($record)) {
            $form->get('account_password')->setAttributes(['required' => 'required']);
            $form->get('account_password_confirm')->setAttributes(['required' => 'required']);
        } else {
            $form->get('account_username')->setAttributes(['disabled' => 'disabled']);
            $form->get('account_password')->setAttributes(['placeholder' => '********']);
            $form->get('account_password_confirm')->setAttributes(['placeholder' => '********']);
        }
        ?>

        <?php echo $this->formViewElement($form->get('group_account_id'));?>
        <?php echo $this->formViewElement($form->get('account_username'));?>
        <?php echo $this->formViewElement($form->get('account_password'));?>
        <?php echo $this->formViewElement($form->get('account_password_confirm'));?>

        <?php echo $this->formViewElement($form->get('account_picture'), 'picture', [
            'pictureValue' => $record['account_picture'],
            'recordId' => $record['account_id'],
            'pictureUrl' => 'public/pictures/users/',
            'pictureDelUrl' => $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture')),
        ]);?>

        <?php echo $this->formViewElement($form->get('account_name'));?>
        <?php echo $this->formViewElement($form->get('account_email'));?>
        <?php echo $this->formViewElement($form->get('account_phone'));?>
        <?php echo $this->formViewElement($form->get('account_status'));?>

        <div class="ln_solid clear"></div>

        <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>





