<div class="pagehding-sec" style='background-image: url("<?php echo $this->basePath('pictures/templates/' . $template[36]['template_picture']);?>")'>
    <div class="pagehding-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-heading">
                    <h1><?php echo $this->escapeHtml($postCategory['category_name_' . $lang]);?></h1>
                    <?php echo $crum;?>
                </div>
            </div>
        </div>
    </div>
</div>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.2993397712394!2d106.81535861517548!3d10.864821892261576!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752754ac3430e7%3A0xec11add37223a477!2zVGjhuqNvIE5ndXnDqm4gU8OgaSBHw7Ju!5e0!3m2!1sen!2s!4v1526397754937" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen=""></iframe>

<div class="contact-page-sec pt-100 pb-100">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <?php
                $form->setAttributes(['action' => $this->url('home-lien-he') . '#contact_form', 'class' => 'contact-form', 'id' => '']);
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="contact-field">
                    <h2><?php echo $this->translate('contact');?></h2>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-input-field">
                            <?php echo $this->formElement($form->get('contact_fullname')); ?>
                            <?php echo $this->formElementErrors($form->get('contact_fullname'), array('class' => 'error-message')); ?>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-input-field">
                            <?php echo $this->formElement($form->get('contact_phone')); ?>
                            <?php echo $this->formElementErrors($form->get('contact_phone'), array('class' => 'error-message')); ?>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12 col-md-12 message-input">
                        <div class="single-input-field">
                            <?php echo $this->formElement($form->get('contact_email')); ?>
                            <?php echo $this->formElementErrors($form->get('contact_email'), array('class' => 'error-message')); ?>
                        </div>
                    </div>
                    <div class="col-md-12 message-input">
                        <div class="single-input-field">
                            <?php echo $this->formElement($form->get('contact_content')); ?>
                            <?php echo $this->formElementErrors($form->get('contact_content'), array('class' => 'error-message')); ?>
                        </div>
                    </div>
                    <div class="col-md-12 single-input-fieldsbtn">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->formHidden($form->get('csrf')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
            <div class="col-md-4">
                <div class="contact-info">
                    <div class="contact-info-item">
                        <div class="contact-info-text">
                            <h2><?php echo $this->translate('phone');?></h2>
                            <?php
                            $phone = explode('/', $template[34]['template_title_' . $lang]);
                            foreach($phone as $v) {
                                echo '<span>' . trim($v) . '</span>';
                            }
                            ?>

                        </div>
                    </div>
                </div>
                <div class="contact-info">
                    <div class="contact-info-item">
                        <div class="contact-info-text">
                            <h2><?php echo $this->translate('email');?></h2>
                            <?php
                             $email = explode(',', $template[33]['template_title_' . $lang]);
                            foreach($email as $v) {
                                echo '<span>' . trim($v) . '</span>';
                            }
                            ?>


                        </div>
                    </div>
                </div>
                <div class="contact-info">
                    <div class="contact-info-item">
                        <div class="contact-info-text">
                            <h2><?php echo $this->translate('address');?></h2>
                            <span><?php echo $template[32]['template_title_' . $lang] ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>