

<div class="pagehding-sec" style='background-image: url("<?php echo $this->basePath('pictures/templates/' . $template[36]['template_picture']);?>")'>
    <div class="pagehding-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-heading">
                    <h1><?php echo $this->escapeHtml($postCategory['category_name_' . $lang]);?></h1>
                    <?php echo $crum;?>
                </div>
            </div>
        </div>
    </div>
</div>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.2993397712394!2d106.81535861517548!3d10.864821892261576!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752754ac3430e7%3A0xec11add37223a477!2zVGjhuqNvIE5ndXnDqm4gU8OgaSBHw7Ju!5e0!3m2!1sen!2s!4v1526397754937" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen=""></iframe>

<div class="contact-page-sec pt-100 pb-100" id="contact_form">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="col-md-12">
                    <div class="alert alert-success" role="alert">
                        <p>Cám ơn Bạn đã liên hệ với chúng tôi.<br>
                            Mọi thắc mắc của bạn sẽ được tư vấn trong thời gian sớm nhất.<br> Nhấn vào <a style="text-decoration: underline" href="<?php echo $this->url('home');?>">đây</a> để trở về trang chủ.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="contact-info">
                    <div class="contact-info-item">
                        <div class="contact-info-text">
                            <h2><?php echo $this->translate('phone');?></h2>
                            <?php
                            $phone = explode('/', $template[34]['template_title_' . $lang]);
                            foreach($phone as $v) {
                                echo '<span>' . trim($v) . '</span>';
                            }
                            ?>

                        </div>
                    </div>
                </div>
                <div class="contact-info">
                    <div class="contact-info-item">
                        <div class="contact-info-text">
                            <h2><?php echo $this->translate('email');?></h2>
                            <?php
                            $email = explode(',', $template[33]['template_title_' . $lang]);
                            foreach($email as $v) {
                                echo '<span>' . trim($v) . '</span>';
                            }
                            ?>


                        </div>
                    </div>
                </div>
                <div class="contact-info">
                    <div class="contact-info-item">
                        <div class="contact-info-text">
                            <h2><?php echo $this->translate('address');?></h2>
                            <span><?php echo $template[32]['template_title_' . $lang] ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>