<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <?php echo $this->partial('admin/partial/language'); ?>

        <?php echo $this->formViewElement($form->get('category_id'));?>
        <?php echo $this->formViewElement($form->get('post_title_vn'), null, ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('post_title_en'), null, ['formGroupClass' => 'field-en']);?>

        <?php echo $this->formViewElement($form->get('post_picture'), 'picture', [
            'pictureValue' => $record['post_picture'],
            'recordId' => $record['post_id'],
            'pictureUrl' => 'public/pictures/posts/',
            'pictureDelUrl' => $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture')),
        ]);?>

        <?php echo $this->formViewElement($form->get('post_quote_vn'), 'textarea', ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('post_quote_en'), 'textarea', ['formGroupClass' => 'field-en']);?>

        <?php echo $this->formViewElement($form->get('post_body_vn'), 'textarea', ['formGroupClass' => 'field-vn']);?>
        <?php echo $this->formViewElement($form->get('post_body_en'), 'textarea', ['formGroupClass' => 'field-en']);?>

        <?php echo $this->formViewElement($form->get('post_status'));?>

        <div class="ln_solid clear"></div>

        <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>



