<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_general_title')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_general_title')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_general_keyword')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_general_keyword')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_general_description')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_general_description')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_general_email')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_general_email')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_general_favicon')); ?>
            <div class="col-md-4 col-sm-4 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_general_favicon')); ?>
            </div>

            <?php if ($record['website_general_favicon']) { ?>
                <div class="col-md-1 col-sm-1 col-xs-12 item">
                    <img title="Click để xóa" class="img-rounded form-users-img" id="picture" onclick="deletePicture(<?php echo $record['website_general_id']; ?>)"
                         style="cursor: pointer"
                         src="<?php echo $this->serverUrl() . '/thumbs/timthumb.php?src=' . $this->basePath('public/pictures/websites/' . $record['website_general_favicon']) . '&w=50px&h=50px'; ?>"/>
                </div>
            <?php } ?>

        </div>

        <div class="ln_solid clear"></div>

        <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

<?php $this->inlineScript()->captureStart();?>
function deleteURL() {
$('input[type="file"]').val('');
$('.picture_upload_view').attr('src', no_image);
}

function deletePicture(id) {
if (confirm('Bạn có muốn xóa?')) {
$.ajax({
url: '<?php echo $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture'));?>',
type: 'post',
data: {id: id},
success: function (response) {
data = jQuery.parseJSON(response);
if (data.return == 1) {
$('#picture').remove();
}
}
});
}
}
<?php $this->inlineScript()->captureEnd();?>



