<div class="x_panel">
    <?php echo $this->partial('admin/partial/form_title', ['moduleName' => $moduleName, 'module' => $module]); ?>
    <?php echo $this->partial('admin/partial/message', ['msgError' => $msgError, 'msgSuccess' => $msgSuccess]); ?>
    <div class="x_content">
        <?php
        $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-label-left', 'id' => 'frm', 'novalidate' => '']);
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_email_system_name')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_email_system_name')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_email_system_host')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_email_system_host')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_email_system_port')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_email_system_port')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_email_system_ssl')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_email_system_ssl')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_email_system_username')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_email_system_username')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('website_email_system_password')); ?>
            <div class="col-md-5 col-sm-5 col-xs-12 item">
                <?php echo $this->formElement($form->get('website_email_system_password')); ?>
            </div>
        </div>

        <div class="ln_solid clear"></div>

        <?php echo $this->partial('admin/partial/form_button', ['form' => $form, 'module' => $module]); ?>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

<?php $this->inlineScript()->captureStart();?>
function deleteURL() {
$('input[type="file"]').val('');
$('.picture_upload_view').attr('src', no_image);
}

function deletePicture(id) {
if (confirm('Bạn có muốn xóa?')) {
$.ajax({
url: '<?php echo $this->url('admin/default', array('controller' => $module, 'action' => 'delete-picture'));?>',
type: 'post',
data: {id: id},
success: function (response) {
data = jQuery.parseJSON(response);
if (data.return == 1) {
$('#picture').remove();
}
}
});
}
}
<?php $this->inlineScript()->captureEnd();?>



