<div class="form-group">
    <div class="col-md-5 col-sm-5 col-xs-12 col-md-offset-3">
        <input type="button" onclick="location.href='<?php echo $this->url('admin/default', ['controller' => $module, 'action' => 'index']);?>'" name="back" id="back" class="btn btn-default" value="Quay về">
        <?php echo $this->formReset($form->get('frmReset')); ?>
        <?php echo $this->formSubmit($form->get('frmSubmit')); ?>
        <?php echo $this->formHidden($form->get('csrf')); ?>
    </div>
</div>