<div class="form-group ">
    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="template_name">Ngôn ngữ</label>
    <div class="col-md-5 col-sm-5 col-xs-12 item">
        <div class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" id="lang_active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Tiếng Việt
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="javascript:void(0)" onclick="changeLanguage('vn')">Tiếng Việt</a>
                </li>
                <li><a href="javascript:void(0)" onclick="changeLanguage('en')">Tiếng Anh</a>
                </li>
            </ul>
        </div>
    </div>
</div>