<div class="x_title">
    <h2><?php echo $moduleName; ?></h2>
    <ul class="nav navbar-right panel_toolbox">
        <li>
            <a href="<?php echo $this->url('admin/default', ['controller' => $module, 'action' => 'add']); ?>">
                <button type="button" class="btn btn-primary">
                    Thêm mới
                </button>
            </a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>