
<!-- top tiles -->
<div class="row tile_count">
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-files-o"></i> Tin tức</span>
        <div class="count green"><?php echo $news;?></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-shield"></i> Dịch vụ</span>
        <div class="count"><?php echo $service;?></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-file-o"></i> Nội dung trang</span>
        <div class="count green"><?php echo $page;?></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-users"></i> Liên hệ</span>
        <div class="count"><?php echo $contact;?></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-archive"></i> Danh mục tin tức</span>
        <div class="count green"><?php echo $newsCategory;?></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-pie-chart"></i> Danh mục dịch vụ</span>
        <div class="count"><?php echo $serviceCategory;?></div>
    </div>
</div>
<!-- /top tiles -->

