<!-- subheader -->
<section id="subheader" data-speed="8" data-type="background" style="background-position: 50% -25px; background: url('<?php echo $this->basePath('public/frontend/images/subheader-1.jpg');?>')">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?php echo $this->escapeHtml($productCategory['product_category_name']);?></h1>
                <?php echo $crum;?>
            </div>
        </div>
    </div>
</section>
<!-- subheader close -->

<div class="container">

    <div class="spacer-single"></div>

    <div id="gallery" class="row gallery full-gallery de-gallery pf_4_cols wow fadeInUp animated" data-wow-delay=".3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp; position: relative; height: 1080px; opacity: 0;">

        <?php foreach($products as $v) {?>
        <!-- gallery item -->
        <div class="col-md-4 col-sm-6 col-xs-12 item mb30 residential" style="position: absolute; left: 0px; top: 0px;">
            <div class="picframe" style="height: 240px;">
                <a href="<?php echo $this->url('home-product-detail', array('name' => $this->function()->formatTitle($v['product_name']), 'id' => $v['product_id']));?>">
                                <span class="overlay" style="opacity: 0; width: 360px; height: 240px;">
                                    <span class="pf_text" style="margin-top: 87px;">
                                        <span class="project-name"><?php echo $this->escapeHtml($v['product_name']);?></span>
                                    </span>
                                </span>
                </a>
                <img src="<?php echo  $this->serverUrl() . '/thumbs/timthumb.php?src=' . $this->basePath('public/pictures/products/' . $v['product_picture']) . '&w=700&h=466';?>" alt="<?php echo $this->escapeHtml($v['product_name']);?>">
            </div>
        </div>
        <!-- close gallery item -->
        <?php }?>
    </div>
    <?php echo $this->paginationControl($products, 'sliding', 'frontend/partial/paginator', array('url' => $this->url('home-product-category', array('name' => $name, 'id' => $id)))); ?>
</div>